/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    FurnaceEngine: {
      address: "0x706947ecc0411badef790282bb89b80126357d9d",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "config",
              type: "tuple",
              internalType: "struct FurnaceEngine.Config",
              components: [
                {
                  name: "router",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "hbarUsdFeed",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "maxOracleAge",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "fuelReserve",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "minSpend",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "scheduledGas",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "dailyBudgetUsd",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxImpactBps",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "priceCeilingUsd",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "slippageBps",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "MAX_IMPACT_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_INTERVAL",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_SLIPPAGE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_INTERVAL",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_SCHEDULED_GAS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "buyback",
          inputs: [],
          outputs: [
            {
              name: "tokensBurned",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimTeamAllocation",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createPool",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "dailyBudgetUsd",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "factory",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISaucerSwapV1Factory",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "fuelReserve",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hbarUsd",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hbarUsdFeed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract AggregatorV3Interface",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "initialize",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "totalSupply",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "decimals",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "liquidityAllocation",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "liquidityUnseeded",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "lpToken",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxImpactBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxOracleAge",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "minSpend",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextRunAt",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pair",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pendingSchedule",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "poolCreationFee",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "previewBuyback",
          inputs: [],
          outputs: [
            {
              name: "skip",
              type: "uint8",
              internalType: "enum FurnaceEngine.Skip",
            },
            {
              name: "spend",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "priceCeilingUsd",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "router",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISaucerSwapV1Router",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "runInterval",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "runScheduled",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "scheduledGas",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "seedLiquidity",
          inputs: [
            {
              name: "minToken",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "minHbar",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "setDailyBudgetUsd",
          inputs: [
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setMaxImpactBps",
          inputs: [
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setPriceCeilingUsd",
          inputs: [
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setSlippageBps",
          inputs: [
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "slippageBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "spentTodayUsd",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "startAutomation",
          inputs: [
            {
              name: "interval",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "status",
          inputs: [],
          outputs: [
            {
              name: "s",
              type: "tuple",
              internalType: "struct FurnaceEngine.Status",
              components: [
                {
                  name: "token",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "pair",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "lpToken",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "totalSupply",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "totalBurned",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "totalSpentHbar",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "spentTodayUsd",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "budgetLeftUsd",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "priceHbar",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "priceUsd",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "hbarUsd",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "reserveHbar",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "reserveToken",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "teamUnclaimed",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "liquidityUnseeded",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "balance",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "fuel",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "nextRunAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "pendingSchedule",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "interval",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "stopAutomation",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "teamUnclaimed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "token",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokenDecimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalBurned",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSpentHbar",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "whbar",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "windowStart",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "AutomationStarted",
          inputs: [
            {
              name: "interval",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AutomationStopped",
          inputs: [],
          anonymous: false,
        },
        {
          type: "event",
          name: "BookingFailed",
          inputs: [
            {
              name: "responseCode",
              type: "int64",
              indexed: false,
              internalType: "int64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Burned",
          inputs: [
            {
              name: "hbarIn",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "tokensBurned",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "priceHbar",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "priceUsd",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "supplyAfter",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BuybackSkipped",
          inputs: [
            {
              name: "reason",
              type: "uint8",
              indexed: false,
              internalType: "enum FurnaceEngine.Skip",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "DailyBudgetSet",
          inputs: [
            {
              name: "dailyBudgetUsd",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Initialized",
          inputs: [
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "totalSupply",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "liquidityAllocation",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "LiquiditySeeded",
          inputs: [
            {
              name: "tokenAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "hbarAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "lpMinted",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MaxImpactSet",
          inputs: [
            {
              name: "maxImpactBps",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolCreated",
          inputs: [
            {
              name: "pair",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "lpToken",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "feeTinybar",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PriceCeilingSet",
          inputs: [
            {
              name: "priceCeilingUsd",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RevenueReceived",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RunBooked",
          inputs: [
            {
              name: "schedule",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "expiry",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ScheduledRun",
          inputs: [
            {
              name: "tokensBurned",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ScheduledRunFailed",
          inputs: [
            {
              name: "reason",
              type: "bytes",
              indexed: false,
              internalType: "bytes",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SlippageSet",
          inputs: [
            {
              name: "slippageBps",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TeamAllocationClaimed",
          inputs: [
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AllocationBreach",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadyInitialized",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadySeeded",
          inputs: [],
        },
        {
          type: "error",
          name: "AutomationActive",
          inputs: [],
        },
        {
          type: "error",
          name: "BadConfig",
          inputs: [],
        },
        {
          type: "error",
          name: "BadInterval",
          inputs: [
            {
              name: "interval",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "BadOraclePrice",
          inputs: [
            {
              name: "answer",
              type: "int256",
              internalType: "int256",
            },
          ],
        },
        {
          type: "error",
          name: "HtsCallFailed",
          inputs: [
            {
              name: "responseCode",
              type: "int64",
              internalType: "int64",
            },
          ],
        },
        {
          type: "error",
          name: "InsufficientFee",
          inputs: [
            {
              name: "required",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "sent",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "NotInitialized",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOwnerOrSelf",
          inputs: [],
        },
        {
          type: "error",
          name: "NothingBought",
          inputs: [],
        },
        {
          type: "error",
          name: "OnlySelf",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "PoolExists",
          inputs: [],
        },
        {
          type: "error",
          name: "PoolMissing",
          inputs: [],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeCastOverflowedIntDowncast",
          inputs: [
            {
              name: "bits",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "value",
              type: "int256",
              internalType: "int256",
            },
          ],
        },
        {
          type: "error",
          name: "SafeCastOverflowedIntToUint",
          inputs: [
            {
              name: "value",
              type: "int256",
              internalType: "int256",
            },
          ],
        },
        {
          type: "error",
          name: "SafeCastOverflowedUintToInt",
          inputs: [
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ScheduleFailed",
          inputs: [
            {
              name: "responseCode",
              type: "int64",
              internalType: "int64",
            },
          ],
        },
        {
          type: "error",
          name: "StaleOracle",
          inputs: [
            {
              name: "updatedAt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "TransferFailed",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroAmount",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41299172,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
